### ISSUE TITLE
Allow nested aquariums

### ISSUE THREAD

**Issue by obiwac** [inobulles/aquarium#27]
See [jail(8)](https://man.freebsd.org/cgi/man.cgi?query=jail&sektion=8).

Basically, the important parts here are:

- [ ] Setting the `children.max` value to something larger than 0 (this doesn't appear in the jail in the `security.jail.param.children.max` sysctl - is this a bug?): #31 
- [ ] Giving the right mounting permissions (`allow.mount.tmpfs` and such).
- [x] This should probably include better control over devfs rulesets and such: #29
- [x] Think about being able to pass generic jail params when creating/entering aquariums: #33

Here are the params which were removed from #28:

```c
JAILPARAM("children.max", "1")
JAILPARAM("allow.mount", "true")
JAILPARAM("allow.mount.devfs", "true")
JAILPARAM("allow.mount.tmpfs", "true")
JAILPARAM("allow.mount.fdescfs", "true")
JAILPARAM("allow.mount.procfs", "true")
JAILPARAM("allow.mount.linsysfs", "true")
JAILPARAM("allow.mount.linprocfs", "true")
```

**Comment by obiwac** [comment]
(Changed the title because nesting jails is only half of the problem.)
